### ISSUE TITLE
minizlib 1.3.x not compatible with node 5 (5.12.0).

### ISSUE THREAD

**Issue by damellis** [isaacs/minizlib#11]
I'm getting this error when doing `node index.js` or `node constants.js` in minizlib 1.3.0, 1.3.1, 1.3.2 with node 5.12.0:

```
/Users/mellisd/Source/libxmljs/node_modules/minizlib/constants.js:2
const { ZLIB_VERNUM } = require('zlib').constants
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/mellisd/Source/libxmljs/node_modules/minizlib/index.js:7:39)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
```

**Comment by isaacs** [comment]
Fixed on 1.3.3.

There will never be another 1.x release.

Please stop using Node 4.  It's insecure.  The node community has moved on.
