### ISSUE TITLE
ZlibError: zlib: invalid code lengths set

### ISSUE THREAD

**Issue by phun-ky** [isaacs/minizlib#8]
I keep on getting these errors in Azure DevOps when using `gulp-zip` that uses your library (from what I can see in the error message).

The build is run on Ubuntu 16.04, and this works fine on my computer with Ubuntu 18.04 and in Windows 10 WSL with Ubuntu Bash.

Node version 8.14.* locally ,in build: . node@10.16.0

```
> @relax/bundle@8.3.1 bundle /home/vsts/work/1/s/packages/bundle
> rimraf ./dist ./*.zip && gulp -L

lerna success exec Executed command in 1 package: "npm run bundle"
lerna ERR! ZlibError: zlib: invalid code lengths set
lerna ERR!     at Unzip.Zlib.(anonymous function) (/home/vsts/work/1/s/node_modules/minizlib/index.js:126:21)
lerna ERR!     at Unzip.emit (events.js:203:15)
lerna ERR!     at Zlib.zlibOnError [as onerror] (zlib.js:165:8)
lerna ERR!     at processChunkSync (zlib.js:403:12)
lerna ERR!     at Unzip.ZlibBase._processChunk (zlib.js:378:12)
lerna ERR!     at Unzip.write (/home/vsts/work/1/s/node_modules/minizlib/index.js:245:30)
lerna ERR!     at Object.write (/home/vsts/work/1/s/node_modules/tar/lib/parse.js:300:58)
lerna ERR!     at Yallist.pipes.forEach.p (/home/vsts/work/1/s/node_modules/minipass/index.js:269:40)
lerna ERR!     at Yallist.forEach (/home/vsts/work/1/s/node_modules/minipass/node_modules/yallist/yallist.js:154:8)
lerna ERR!     at ReadStream.emit (/home/vsts/work/1/s/node_modules/minipass/index.js:269:20)
lerna ERR!     at ReadStream.emit (/home/vsts/work/1/s/node_modules/fs-minipass/index.js:153:22)
lerna ERR!     at ReadStream.write (/home/vsts/work/1/s/node_modules/minipass/index.js:102:17)
lerna ERR!     at ReadStream.[_handleChunk] (/home/vsts/work/1/s/node_modules/fs-minipass/index.js:130:19)
lerna ERR!     at ReadStream.[_onread] (/home/vsts/work/1/s/node_modules/fs-minipass/index.js:108:32)
lerna ERR!     at fs.read (/home/vsts/work/1/s/node_modules/fs-minipass/index.js:100:22)
lerna ERR! lerna zlib: invalid code lengths set
```

**Comment by isaacs** [comment]
This is an error coming from zlib itself.

Just out of curiosity, are you trying to unpack zip files, or tgz files?

**Comment by isaacs** [comment]
Digging a little bit deeper, this is especially curious.  gulp-zip doesn't use minizlib or tar, and neither do any of its dependencies.  But it definitely looks like _something_ is trying to do a `tar.extract` on a file that is not a gzipped tar archive.

**Comment by phun-ky** [comment]
I will try to dig up some more info from our builds. Stay tuned. 
null

**Comment by phun-ky** [comment]
Here is the log from the build:

![Screenshot from 2019-10-02 13-47-54](https://user-images.githubusercontent.com/1714029/66041939-6ac9d280-e51b-11e9-8239-928e317c332a.png)

The failing task is `npm run bundle` which is `gulp -L`. The gulpfile looks like this:

<details>
  <summary>gulpfile.js</summary>

```javascript
const gulp = require('gulp');
const stylus = require('gulp-stylus');
const rename = require('gulp-rename');
const stylint = require('gulp-stylint');
const sourcemaps = require('gulp-sourcemaps');
const cssnano = require('gulp-cssnano');
const banner = require('gulp-banner');
const gulpZip = require('gulp-zip');
const insert = require('gulp-insert');

const gulpHelpers = require('../../lib/gulp-helpers');
const pkg = require('./package.json');

const buildDev = () =>
  gulp
    .src('./src/bundle.styl')
    .pipe(stylus(require('../../config/stylus.dev.config.js')))
    .pipe(rename('relax.css'))
    .pipe(gulp.dest('./dist/'));
buildDev.displayName = 'Build development files';
const buildProd = () =>
  gulp
    .src('./src/bundle.styl')
    .pipe(stylint())
    .pipe(stylint.reporter())
    .pipe(stylus(require('../../config/stylus.prod.config.js')))
    .pipe(rename('relax.min.css'))
    .pipe(sourcemaps.init())
    .pipe(cssnano(require('../../config/cssnano.config.js')))
    .pipe(
      banner(gulpHelpers.banner, {
        pkg: pkg
      })
    )
    .pipe(sourcemaps.write('.'))
    .pipe(gulp.dest('./dist/'));
buildProd.displayName = 'Build production files';
const zipDist = () =>
  gulp
    .src('./dist/**/*')
    .pipe(gulpZip(`${pkg.name.replace('@relax/bundle', '')}relax.zip`))
    .pipe(gulp.dest('./dist'));
zipDist.displayName = 'Zip files for distribution';

const buildWebcomponent = () =>
  gulp
    .src('./dist/relax.min.css')
    .pipe(
      insert.wrap(
        '<dom-module id="relax-styles"><template><custom-style><style>',
        '</style></template></custom-style></dom-module>'
      )
    )
    .pipe(rename('relax.webcomponent.html'))
    .pipe(gulp.dest('./dist'));
buildWebcomponent.displayName = 'Build web component file';

const zipFonts = () =>
  gulp
    .src('./dist/fonts/*')
    .pipe(gulpZip(`${pkg.name.replace('@relax/bundle', '')}relax-fonts.zip`))
    .pipe(gulp.dest('./dist'));
zipFonts.displayName = 'Zip fonts for distribution';

const zipIcons = () =>
  gulp
    .src(['./dist/icons/*', './dist/loaders/*'])
    .pipe(gulpZip(`${pkg.name.replace('@relax/bundle', '')}relax-icons.zip`))
    .pipe(gulp.dest('./dist'));
zipIcons.displayName = 'Zip icons for distribution';

const build = gulp.series(gulpHelpers.lint, gulp.parallel(buildDev, buildProd), buildWebcomponent);
const copy = gulp.parallel(gulpHelpers.copyFonts, gulpHelpers.copyAllIconFiles);
const zip = gulp.series(zipDist, zipFonts, zipIcons);
const _default = gulp.series(build, copy, zip);

gulp.task('default', _default);
gulp.task('lint', gulpHelpers.lint);
gulp.task('zip', zip);
gulp.task('build', gulp.series(gulpHelpers.cleanDist, build));

```
</details>

And the versions are:

<details>
  <summary>package.json</summary>
{
  "name": "@relax/bundle",
  "version": "8.3.4",
  "scripts": {
    "bundle": "rimraf ./dist ./*.zip && gulp -L"
  },
  "devDependencies": {
    "gulp": "^4.0.0",
    "gulp-banner": "^0.1.3",
    "gulp-cssnano": "^2.1.3",
    "gulp-insert": "^0.5.0",
    "gulp-rename": "^1.4.0",
    "gulp-sourcemaps": "^2.6.4",
    "gulp-stylint": "^4.0.2",
    "gulp-stylus": "^2.7.0",
    "gulp-theo": "^2.0.0",
    "gulp-zip": "^4.2.0",
    "prettier": "^1.13.7",
    "rimraf": "^2.6.2",
    "theo": "^8.1.3"
  },
  "dependencies": {
    "@relax/badges": "^8.3.4",
    "@relax/breakpoints": "^8.3.4",
    "@relax/buttons": "^8.3.4",
    "@relax/cards": "^8.3.4",
    "@relax/color": "^8.3.4",
    "@relax/core": "^8.3.4",
    "@relax/dialog": "^8.3.4",
    "@relax/emblem": "^8.3.4",
    "@relax/forms": "^8.3.4",
    "@relax/global-header": "^8.3.4",
    "@relax/grid": "^8.3.4",
    "@relax/icons": "^8.3.4",
    "@relax/list": "^8.3.4",
    "@relax/loader": "^8.3.4",
    "@relax/media": "^8.3.4",
    "@relax/menu": "^8.3.4",
    "@relax/mesh": "^8.3.4",
    "@relax/modal": "^8.3.4",
    "@relax/notifications": "^8.3.4",
    "@relax/pagination": "^8.3.4",
    "@relax/panel": "^8.3.4",
    "@relax/placeholder": "^8.3.4",
    "@relax/popover": "^8.3.4",
    "@relax/search": "^8.3.4",
    "@relax/selection-controls": "^8.3.4",
    "@relax/sliders": "^8.3.4",
    "@relax/stepper": "^8.3.4",
    "@relax/tables": "^8.3.4",
    "@relax/tabs": "^8.3.4",
    "@relax/text-field": "^8.3.4",
    "@relax/timeline": "^8.3.4",
    "@relax/tooltip": "^8.3.4",
    "@relax/typography": "^8.3.4",
    "@relax/util": "^8.3.4",
    "normalize.css": "^8.0.0"
  }
}

</details

npm version 6.5.0

**Comment by phun-ky** [comment]
Only reference I found in `lerna` for zipping is the `packDirectory` function: https://github.com/lerna/lerna/blob/master/utils/pack-directory/lib/pack-directory.js#L47

Using `lerna@3.5.1` currently

**Comment by iartemiev** [comment]
We're experiencing something quite similar with our Lerna publish job running in CircleCI.

As @phun-ky said, it happens randomly. Roughly every 20 publishes or so. Simply re-running the failed job with the same code will get it to pass every time. 

Node version is 12.16.1

Lerna appears to be using minizlib@1.3.3 : https://github.com/lerna/lerna/blob/master/package-lock.json#L6861

Very hard to debug this, as there's no discernible pattern for when it errors out.

```bash
lerna info auto-confirmed 
lerna info publish Publishing packages to npm...
lerna info Verifying npm credentials
lerna http fetch GET 200 https://registry.npmjs.org/-/npm/v1/user 261ms
lerna http fetch GET 200 https://registry.npmjs.org/-/org/aws-amplify-ops/package?format=cli 399ms
lerna info Checking two-factor auth mode
lerna http fetch GET 200 https://registry.npmjs.org/-/npm/v1/user 410ms
lerna ERR! ZlibError: zlib: invalid literal/length code
lerna ERR!     at Unzip.<anonymous> (/root/amplify-js/node_modules/minizlib/index.js:73:52)
lerna ERR!     at Unzip.emit (events.js:323:22)
lerna ERR!     at Zlib.zlibOnError [as onerror] (zlib.js:183:8)
lerna ERR!     at Zlib.writeSync (<anonymous>)
lerna ERR!     at processChunkSync (zlib.js:426:12)
lerna ERR!     at Unzip.ZlibBase._processChunk (zlib.js:401:12)
lerna ERR!     at Unzip.write (/root/amplify-js/node_modules/minizlib/index.js:140:30)
lerna ERR!     at Object.write (/root/amplify-js/node_modules/tar/lib/parse.js:305:58)
lerna ERR!     at Yallist.<anonymous> (/root/amplify-js/node_modules/fs-minipass/node_modules/minipass/index.js:374:18)
lerna ERR!     at Yallist.forEach (/root/amplify-js/node_modules/yallist/yallist.js:156:8)
lerna ERR!     at ReadStream.emit (/root/amplify-js/node_modules/fs-minipass/node_modules/minipass/index.js:373:20)
lerna ERR!     at ReadStream.emit (/root/amplify-js/node_modules/fs-minipass/index.js:154:22)
lerna ERR!     at ReadStream.write (/root/amplify-js/node_modules/fs-minipass/node_modules/minipass/index.js:163:17)
lerna ERR!     at ReadStream.[_handleChunk] (/root/amplify-js/node_modules/fs-minipass/index.js:131:19)
lerna ERR!     at ReadStream.[_onread] (/root/amplify-js/node_modules/fs-minipass/index.js:109:32)
lerna ERR! lerna zlib: invalid literal/length code
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by phun-ky** [comment]
Got the same today

```bash
lerna info git Pushing tags...
lerna WARN gitPush fatal: the receiving end does not support --atomic push
lerna WARN gitPush fatal: the remote end hung up unexpectedly
lerna WARN gitPush error: failed to push some refs to 'https://dev.azure.com/if-it/If%20Design%20Hub/_git/guybrush'
lerna WARN gitPush 
lerna info gitPush --atomic failed, attempting non-atomic push
lerna info publish Publishing packages to npm...
lerna notice Skipping all user and access validation due to third-party registry
lerna notice Make sure you're authenticated properly ¯\_(ツ)_/¯
lerna ERR! ZlibError: zlib: invalid distance too far back
lerna ERR!     at Unzip.<anonymous> (/home/vsts/work/1/s/node_modules/minizlib/index.js:73:52)
lerna ERR!     at Unzip.emit (events.js:327:22)
lerna ERR!     at Zlib.zlibOnError [as onerror] (zlib.js:183:8)
lerna ERR!     at Zlib.writeSync (<anonymous>)
lerna ERR!     at processChunkSync (zlib.js:426:12)
lerna ERR!     at Unzip.ZlibBase._processChunk (zlib.js:401:12)
lerna ERR!     at Unzip.write (/home/vsts/work/1/s/node_modules/minizlib/index.js:140:30)
lerna ERR!     at Object.write (/home/vsts/work/1/s/node_modules/@lerna/get-packed/node_modules/tar/lib/parse.js:305:58)
lerna ERR!     at Yallist.<anonymous> (/home/vsts/work/1/s/node_modules/minipass/index.js:374:18)
lerna ERR!     at Yallist.forEach (/home/vsts/work/1/s/node_modules/minipass/node_modules/yallist/yallist.js:156:8)
lerna ERR!     at ReadStream.emit (/home/vsts/work/1/s/node_modules/minipass/index.js:373:20)
lerna ERR!     at ReadStream.emit (/home/vsts/work/1/s/node_modules/fs-minipass/index.js:154:22)
lerna ERR!     at ReadStream.write (/home/vsts/work/1/s/node_modules/minipass/index.js:163:17)
lerna ERR!     at ReadStream.[_handleChunk] (/home/vsts/work/1/s/node_modules/fs-minipass/index.js:131:19)
lerna ERR!     at ReadStream.[_onread] (/home/vsts/work/1/s/node_modules/fs-minipass/index.js:109:32)
lerna ERR! lerna zlib: invalid distance too far back

https://github.com/lerna/lerna/issues/2278#issuecomment-642475494
```

**Comment by phun-ky** [comment]
These are my builds the last 5 days, it's getting annoying and breaks Semver (since the publishing of packages fails due to this). Do you have any lead on what it could be?

![image](https://user-images.githubusercontent.com/1714029/84883834-53268000-b091-11ea-971f-507d36548839.png)

![image](https://user-images.githubusercontent.com/1714029/84884209-b6b0ad80-b091-11ea-9989-9f8ab985f7aa.png)

**Comment by phun-ky** [comment]
Hm, when I switched from ubuntu 16.04 to 18.04, it went straight through after 4 failed attempts. Could it be an outdated zlib on 16.04?

**Comment by phun-ky** [comment]
https://github.com/lerna/lerna/issues/2278#issuecomment-652538695 it might be a dep issue with `npm pack `

**Comment by phun-ky** [comment]
Do not know if this is related @isaacs , but now after upgrading to npm 8 and node 16, I get these errors:

```
lerna ERR! ZlibError: zlib: invalid block type
lerna ERR!     at Unzip.write (/home/alexander/Workspace/if/ids-core/node_modules/minizlib/index.js:154:22)
lerna ERR!     at Object.write (/home/alexander/Workspace/if/ids-core/node_modules/tar/lib/parse.js:354:57)
lerna ERR!     at Yallist.<anonymous> (/home/alexander/Workspace/if/ids-core/node_modules/minipass/index.js:384:18)
lerna ERR!     at Yallist.forEach (/home/alexander/Workspace/if/ids-core/node_modules/minipass/node_modules/yallist/yallist.js:156:8)
lerna ERR!     at ReadStream.emit (/home/alexander/Workspace/if/ids-core/node_modules/minipass/index.js:383:20)
lerna ERR!     at ReadStream.emit (/home/alexander/Workspace/if/ids-core/node_modules/fs-minipass/index.js:175:22)
lerna ERR!     at ReadStream.write (/home/alexander/Workspace/if/ids-core/node_modules/minipass/index.js:168:12)
lerna ERR!     at ReadStream.[_handleChunk] (/home/alexander/Workspace/if/ids-core/node_modules/fs-minipass/index.js:146:19)
lerna ERR!     at ReadStream.[_onread] (/home/alexander/Workspace/if/ids-core/node_modules/fs-minipass/index.js:123:32)
lerna ERR! lerna zlib: invalid block type
```

The only solution proposed is only for `yarn`: https://github.com/lerna/lerna/issues/2278 , but I see some others has experienced this exact error before: https://stackoverflow.com/questions/67228250/lerna-err-zliberror-zlib-invalid-block-type-while-publishing-packages-in-lern#_=_. Should I create a new issue for this or is this similar?

**Comment by isaacs** [comment]
Is this still an issue?

**Comment by phun-ky** [comment]
Thanks for getting back. I don't know, since I left that client last year :/
